config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: "dashboard"
    get "summary", to: "orders_summary#index", as: "summary"
    post "summary/download_csv", to: "orders_summary#download_csv", as: "download_csv"
    get "summary/check_job_status", to: "orders_summary#check_job_status", as: "check_job_status"
    get "summary/download_orders_csv", to: "orders_summary#download_orders_csv", as: "download_orders_csv"
  end
  resources :users, only: [:index]
  root "static_pages#home"
  post "signup", to: "users#create"
  get "signup", to: "users#new"
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  post "login", to: "sessions#create"
  get "login", to: "sessions#new"
  delete "logout", to: "sessions#destroy"
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  put "profile", to: "users#update"
  get "profile", to: "users#edit"
  delete "profile", to: "users#destroy"
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :carts, only: [:index], path: "cart"
  resources :items, only: [:create, :destroy]
  post "items/:id/add", to: "items#add", as: "add_item"
  delete "items/:id/remove", to: "items#remove", as: "remove_item"
  resources :orders, only: [:index, :show, :new, :create]
  delete "orders/:id/cancel", to: "orders#cancel", as: "cancel_order"
  get "orders/:id/pay", to: "orders#pay", as: "pay_order"
  post "orders/:id/ship", to: "orders#ship", as: "ship_order"
  post "orders/:id/receive", to: "orders#receive", as: "receive_order"
  post "orders/:id/pay", to: "orders#paid", as: "paid_order"
  resources :categories, only: [:index, :create, :destroy, :update, :edit, :new]
  resources :wishlists, only: [:index, :create, :destroy], path: "wishlist"
  post "wishlist/add/:product_id", to: "wishlists#create", as: "wishlist_add"
  delete "wishlist/remove/:product_id", to: "wishlists#destroy", as: "wishlist_remove"
  post "cart/add/:product_id", to: "items#create", as: "cart_add"
  delete "users/:id/disable", to: "users#disable", as: "disable_user"
  post "users/:id/enable", to: "users#enable", as: "enable_user"
  resources :reviews, only: [:create, :destroy]
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  has_many :products, through: :items

  def subtotal
    items.map(&:total_price).sum
  end

  def shipping
    0.00
  end

  def total
    subtotal + shipping
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cart = current_user.cart
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/index.html.erb
<% if current_user.cart.items.any? %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>Your Cart</h2>
      <% @cart.items.each do |item| %>
        <div class="row">
          <div class="col-md-2">
            <% if item.product.image.attached? %>
              <%= image_tag item.product.image.variant(:thumb), class: "img-fluid" %>
            <% end %>
          </div>
          <div class="col-md-10">
            <h4><%= item.product.name %></h4>
            <p>
              <% if item.quantity >1 %>
                <%= link_to "-", remove_item_path(item), data: { "turbo-method": :delete  } %>
              <% else %>
                <%= link_to "-", item_path(item), data: { "turbo-method": :delete } %>
              <% end %>
             <%= number_to_currency(item.product.price) %> x <%= item.quantity %>
              <%= link_to "+", add_item_path(item), data: { "turbo-method": :post } %>
             </p>
          </div>
        </div>
        <hr>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <h4>Subtotal: <%= number_to_currency(@cart.subtotal) %></h4>
          <hr>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <h2>Summary</h2>
      <div class="panel panel-default">
        <div class="panel-body">
          <p>Subtotal: <%= number_to_currency(@cart.subtotal) %></p>
          <p>Shipping: <%= number_to_currency(@cart.shipping) %></p>
          <hr>
          <h4>Total: <%= number_to_currency(@cart.total) %></h4>
          <%= link_to "Proceed to checkout", new_order_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Your cart is empty</h2>
      </div>
    </div>
  </div>
<% end %>

app/views/carts/show.html.erb
<% if current_user.cart.items.any? %>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>Your Cart</h2>
      <% @cart.items.each do |item| %>
        <div class="row">
          <div class="col-md-2">
            <% if item.product.image.attached? %>
              <%= image_tag item.product.image.variant(:thumb), class: "img-fluid" %>
            <% end %>
          </div>
          <div class="col-md-10">
            <h4><%= item.product.name %></h4>
            <p>
              <% if item.quantity >1 %>
                <%= link_to "-", remove_item_path(item), data: { "turbo-method": :delete  } %>
              <% else %>
                <%= link_to "-", item_path(item), data: { "turbo-method": :delete } %>
              <% end %>
             <%= number_to_currency(item.product.price) %> x <%= item.quantity %>
              <%= link_to "+", add_item_path(item), data: { "turbo-method": :post } %>
             </p>
          </div>
        </div>
        <hr>
      <% end %>
      <div class="row">
        <div class="col-md-12">
          <h4>Subtotal: <%= number_to_currency(@cart.subtotal) %></h4>
          <hr>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <h2>Summary</h2>
      <div class="panel panel-default">
        <div class="panel-body">
          <p>Subtotal: <%= number_to_currency(@cart.subtotal) %></p>
          <p>Shipping: <%= number_to_currency(@cart.shipping) %></p>
          <hr>
          <h4>Total: <%= number_to_currency(@cart.total) %></h4>
          <%= link_to "Proceed to checkout", new_order_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Your cart is empty</h2>
      </div>
    </div>
  </div>
<% end %>