config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: "dashboard"
    get "summary", to: "orders_summary#index", as: "summary"
    post "summary/download_csv", to: "orders_summary#download_csv", as: "download_csv"
    get "summary/check_job_status", to: "orders_summary#check_job_status", as: "check_job_status"
    get "summary/download_orders_csv", to: "orders_summary#download_orders_csv", as: "download_orders_csv"
  end
  resources :users, only: [:index]
  root "static_pages#home"
  post "signup", to: "users#create"
  get "signup", to: "users#new"
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  post "login", to: "sessions#create"
  get "login", to: "sessions#new"
  delete "logout", to: "sessions#destroy"
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  put "profile", to: "users#update"
  get "profile", to: "users#edit"
  delete "profile", to: "users#destroy"
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :carts, only: [:index], path: "cart"
  resources :items, only: [:create, :destroy]
  post "items/:id/add", to: "items#add", as: "add_item"
  delete "items/:id/remove", to: "items#remove", as: "remove_item"
  resources :orders, only: [:index, :show, :new, :create]
  delete "orders/:id/cancel", to: "orders#cancel", as: "cancel_order"
  get "orders/:id/pay", to: "orders#pay", as: "pay_order"
  post "orders/:id/ship", to: "orders#ship", as: "ship_order"
  post "orders/:id/receive", to: "orders#receive", as: "receive_order"
  post "orders/:id/pay", to: "orders#paid", as: "paid_order"
  resources :categories, only: [:index, :create, :destroy, :update, :edit, :new]
  resources :wishlists, only: [:index, :create, :destroy], path: "wishlist"
  post "wishlist/add/:product_id", to: "wishlists#create", as: "wishlist_add"
  delete "wishlist/remove/:product_id", to: "wishlists#destroy", as: "wishlist_remove"
  post "cart/add/:product_id", to: "items#create", as: "cart_add"
  delete "users/:id/disable", to: "users#disable", as: "disable_user"
  post "users/:id/enable", to: "users#enable", as: "enable_user"
  resources :reviews, only: [:create, :destroy]
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :wishlists
  has_many :reviews, dependent: :destroy
  has_many :items, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :price, presence: true, numericality: { greater_than: 0, only_integer: false }
  has_one_attached :image do |attachable|
    attachable.variant(:thumb, resize_to_limit: [150, 150])
    attachable.variant(:medium, resize_to_limit: [300, 300])
    attachable.variant(:large, resize_to_limit: [500, 500])
  end
  validates :image,
    attached: false,
    content_type: { in: ["image/png", "image/jpg", "image/jpeg"], message: "must be a valid image format" },
    size: { less_than: 5.megabytes, message: "should be less than 5MB" }
  before_save :set_default_image
  scope :by_category, ->(category_ids) { joins(:categories).where(categories: { id: category_ids }).distinct }
  scope :by_search, ->(search) { where("products.name LIKE ?", "%#{search}%") }
  scope :by_min_price, ->(min_price) { where("products.price >= ?", min_price) }
  scope :by_max_price, ->(max_price) { where("products.price <= ?", max_price) }

  def self.search(params)
    all = Product.all
    all = all.by_category(params[:category_ids]) if params[:category_ids].present?
    all = all.by_search(params[:search]) if params[:search].present?
    all = case params[:sort_by]
    when "name" then all.order(name: :asc)
    when "name_desc" then all.order(name: :desc)
    when "price" then all.order(price: :asc)
    when "price_desc" then all.order(price: :desc)
    else all
    end
    all = all.by_min_price(params[:min_price]) if params[:min_price].present?
    all = all.by_max_price(params[:max_price]) if params[:max_price].present?
    all
  end

  def average_rating
    if reviews.count.positive?
      reviews.average(:rating).round(1)
    else
      0
    end
  end

  private

  def set_default_image
    return if image.attached?

    image.attach(
      io: File.open(Rails.root.join("app", "assets", "images", "default_product.png")),
      filename: "default_product.png",
      content_type: "image/png",
    )
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]

  def index
    @pagy, @products = pagy(Product.all, items: 12)
  end

  def show
    @product = Product.find_by(id: params[:id])
    return unless @product.nil?

    flash[:alert] = "Product not found"
    redirect_to(root_url)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.image.attach(params[:product][:image])

    unless params[:product][:category_ids].nil?
      params[:product][:category_ids][1..].each do |category_id|
        @product.categories << Category.find_by(id: category_id)
      end
    end

    if @product.save
      flash[:success] = "Product created"
      redirect_to(@product)
    else
      flash.now[:alert] = "Product not created"
      render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @product = Product.find_by(id: params[:id])
  end

  def update
    @product = Product.find_by(id: params[:id])
    @product.update(product_params)

    @product.categories.clear
    unless params[:product][:category_ids].nil?
      params[:product][:category_ids][1..].each do |category_id|
        @product.categories << Category.find_by(id: category_id)
      end
    end

    if @product.save
      flash[:success] = "Product updated"
      redirect_to(@product)
    else
      flash.now[:alert] = "Product not updated"
      render(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy
    flash[:success] = "Product deleted"
    redirect_back_or_to(root_url)
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_product.html.erb
<div>
  <div class="col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= product.name %></h3>
        <p><%= product.description[0,75] %>...</p>
        <p>
          <strong>Price: <%= number_to_currency product.price %></strong>
        </p>
        <p>
          <%= link_to "Show", product, class: "btn btn-primary" %>
          <%= link_to "Edit", edit_product_path(product), class: "btn btn-warning" %>
          <%= link_to "Destroy", product, data: {"turbo-method": :delete, turbo_confirm: "You sure?"},class: "btn btn-danger" %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/products/_product_form.html.erb
<div class="my-form">
  <div class="form" data-controller="imagesize">
    <%= form_with model: @product do |f| %>
      <%= render 'shared/form_errors', object: f.object %>

      <div class="mb-3">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :description, class: "form-label" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :price, class: "form-label" %>
        <%= f.number_field :price, step: :any, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :category_ids, "Categories", class: "form-label" %>
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <div class="form-check">
            <%= cb.check_box(class: "form-check-input") %>
            <%= cb.label(class: "form-check-label") %>
          </div>
        <% end %>
      </div>

      <div class="mb-3">
        <%= f.label :image, class: "form-label" %>
        <%= f.file_field :image, accept: "image/jpeg, image/jpg, image/png", class: "form-control", "data-imagesize-target": "input" %>
      </div>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<% provide(:button_text, "Save changes") %>
<%= render 'product_form'%>

app/views/products/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4">All products</h1>
  <%= link_to "New", new_product_path, class: "btn btn-success", style:"margin: 20px;"%>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Product</th>
          <th>Price</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td>
              <a href="<%= product_path(product) %>">
                <%= product.name %>
              </a>
            </td>
            <td>$<%= product.price %></td>


            <td>
            <%= link_to "View Order", product_path(product), class: "btn btn-primary" %>
            <%= link_to "Edit", edit_product_path(product), class: "btn btn-warning" %>
            <%= link_to "Destroy", product, data: {"turbo-method": :delete, turbo_confirm: "You sure?"},class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/products/new.html.erb
<% provide(:button_text, "Create product") %>
<%= render 'product_form' %>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <% if current_user.admin? %>
      <div class="col-md-12 mb-4">
        <%= link_to "Destroy", @product, data: {"turbo-method": :delete, turbo_confirm: "You sure?"}, class: "btn btn-danger" %>
        <%= link_to "Edit", edit_product_path(@product), class: "btn btn-warning" %>
      </div>
    <% end %>
    <% unless current_user.wishlist.products.include?(@product) %>
      <div class="col-md-12 mb-4">
        <%= link_to "Add to Wishlist", wishlist_add_path(@product), data: {"turbo-method": :post}, class: "btn btn-primary" %>
      </div>
    <% end %>

    <div class="col-md-5">
      <% if @product.image.attached? %>
      <%= image_tag @product.image.variant(:large), class: "img-fluid" %>
      <% end %>
    </div>
    <div class="col-md-7">
      <h2><%= @product.name %></h2>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">Price:</th>
            <td><%= number_to_currency(@product.price) %></td>
          </tr>
          <tr>
            <th scope="row">Description:</th>
            <td><%= @product.description %></td>
          </tr>
        </tbody>
      </table>
      <%= link_to "Add to cart", cart_add_path(@product), data: {"turbo-method": :post}, class: "btn btn-primary" %>
    </div>
  </div>

  <% unless current_user.reviews.find_by(product_id: @product.id) %>
  <div class="row">
    <div class="col-md-12">
      <h3>Add a review</h3>
      <%= form_with url: reviews_path, model: @review, scope: :review do |f| %>
        <%= f.hidden_field :product_id, value: @product.id %>
        <div class="mb-3">
          <%= f.label :rating, class: "form-label" %>
          <%= f.number_field :rating, class: "form-control", max: 5, min: 1 %>
        </div>
        <div class="mb-3">
          <%= f.label :content, class: "form-label" %>
          <%= f.text_area :content, class: "form-control" %>
        </div>
        <%= f.submit "Submit", class: "btn btn-primary mt-2" %>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <h3>Reviews</h3>
      <% if @product.reviews.any? %>
        <p>
          <%= @product.average_rating %>/5
          <span style="font-size: 12px">(<%= pluralize @product.reviews.count, "review" %>)</span>
        </p>

        <% @product.reviews.each do |review| %>
          <div class="card mb-4">
            <div class="card-body">
              <p><%= review.content %></p>
              <p class="text-muted"><%= review.rating%>/5 by <%= review.user.name %>
                <% if review.user == current_user %>
              <%= link_to "(delete)", review, data: {"turbo-method": :delete, turbo_confirm: "You sure?"}, style: "font-size:14px;" %>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>No reviews yet</p>
  <% end %>
</div>
</div>
</div>
</div>