config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    get "dashboard", to: "dashboard#index", as: "dashboard"
    get "summary", to: "orders_summary#index", as: "summary"
    post "summary/download_csv", to: "orders_summary#download_csv", as: "download_csv"
    get "summary/check_job_status", to: "orders_summary#check_job_status", as: "check_job_status"
    get "summary/download_orders_csv", to: "orders_summary#download_orders_csv", as: "download_orders_csv"
  end
  resources :users, only: [:index]
  root "static_pages#home"
  post "signup", to: "users#create"
  get "signup", to: "users#new"
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  post "login", to: "sessions#create"
  get "login", to: "sessions#new"
  delete "logout", to: "sessions#destroy"
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  put "profile", to: "users#update"
  get "profile", to: "users#edit"
  delete "profile", to: "users#destroy"
  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :carts, only: [:index], path: "cart"
  resources :items, only: [:create, :destroy]
  post "items/:id/add", to: "items#add", as: "add_item"
  delete "items/:id/remove", to: "items#remove", as: "remove_item"
  resources :orders, only: [:index, :show, :new, :create]
  delete "orders/:id/cancel", to: "orders#cancel", as: "cancel_order"
  get "orders/:id/pay", to: "orders#pay", as: "pay_order"
  post "orders/:id/ship", to: "orders#ship", as: "ship_order"
  post "orders/:id/receive", to: "orders#receive", as: "receive_order"
  post "orders/:id/pay", to: "orders#paid", as: "paid_order"
  resources :categories, only: [:index, :create, :destroy, :update, :edit, :new]
  resources :wishlists, only: [:index, :create, :destroy], path: "wishlist"
  post "wishlist/add/:product_id", to: "wishlists#create", as: "wishlist_add"
  delete "wishlist/remove/:product_id", to: "wishlists#destroy", as: "wishlist_remove"
  post "cart/add/:product_id", to: "items#create", as: "cart_add"
  delete "users/:id/disable", to: "users#disable", as: "disable_user"
  post "users/:id/enable", to: "users#enable", as: "enable_user"
  resources :reviews, only: [:create, :destroy]
end

app/views/layouts/_flash.html.erb
<div data-controller="alert">
  <% flash.each do |key, value| %> 
    <div class="alert alert-<%= key == "success" ? "success" : "info" %>" data-target="alert.alert">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <%= link_to "Ecomm", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <% if logged_in? %>
      <form class="d-flex mx-auto my-2 my-lg-0" action="<%= root_path %>" method="get">
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search products..." %>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </div>
        <% if params[:category_ids].present? %>
          <% params[:category_ids].each do |id| %>
            <%= hidden_field_tag "category_ids[]", id, multiple: true %>
          <% end %>
        <% end %>

        <% if params[:sort_by].present? %>
          <%= hidden_field_tag "sort_by", params[:sort_by] %>
        <% end %>

        <% if params[:min_price].present? %>
          <%= hidden_field_tag "min_price", params[:min_price] %>
        <% end %>

        <% if params[:max_price].present? %>
          <%= hidden_field_tag "max_price", params[:max_price] %>
        <% end %>

      </form>
      <% end %>
      <ul class="navbar-nav ms-auto">
        <% if logged_in? %>
        <li class="nav-item"><%= link_to "Cart", carts_path, class: "nav-link" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="accountDropdown">
            <% if admin? %>
            <li><%= link_to "Admin dashboard", admin_dashboard_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <% end %>
            <li><%= link_to "Profile", profile_path, class: "dropdown-item" %></li>
            <li><%= link_to "Wishlist", wishlists_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= link_to "Log out", logout_path, class: "dropdown-item",
                data: { "turbo-method": :delete } %>
            </li>
          </ul>
        </li>
        <% else %>
        <li class="nav-item"><%= link_to "Sign up", signup_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecomm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
       <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>